language: python
python:
  - "3.8"
cache: pip
install:
  - python setup.py develop
  - pip uninstall qiskit
  - pip install qiskit ase  numpy==1.18.5 scipy==1.4.1 matplotlib>=3.0.0 phonopy==2.8.1 coverage lightgbm==2.1.0  flask joblib networkx scikit-learn pandas pennylane   codecov torch keras tensorflow==2.3.0  pytest pytest-cov bokeh
  #- pip install -r requirements-for-ci-only.txt
  #- python setup.py develop
  - pip install git+https://github.com/aspuru-guzik-group/tequila.git
script:
  - coverage run -m pytest
  - coverage report -m
